In [1]:
import pandas as pd

# Topics for the Day
1. pd.merge()
2. pd.apply()
3. pd.groupby()
4. Group-based Aggregation
5. Group-based Filtering
6. Group-based Apply

In [2]:
df_trader = pd.read_excel("../pandas-trader/stock_trader.xlsx", sheet_name='TRADES')
df_trader.tail()

,DP ID,Client ID,Broker,Transaction Date,Exchange,Scrip,Order Direction,Quantity,Share Price (₹),Brokerage (₹),ETC (₹),SEBI+ (₹),GST (₹),STT (₹),SD (₹),Transaction Time
251,12765333,26657514,Zerodha,2024-10-10 00:00:00,NSE,IOB,BUY,150,54.55,15.0,0.243020,0.016365,2.746689,8.18250,1.0,14:42:44
252,12765333,26657514,Zerodha,2024-10-10 00:00:00,NSE,GMDCLTD,BUY,25,326.40,15.0,0.242352,0.016320,2.746561,8.16000,1.0,15:20:53
253,12765333,26657514,Zerodha,2024-10-10 00:00:00,NSE,FLUOROCHEM,SELL,2,4585.00,15.0,0.272349,0.018340,2.752324,9.17000,0.0,10:12:49
254,12765333,26657514,Zerodha,2024-10-15 00:00:00,NSE,BAJAJHFL,BUY,13,138.47,15.0,0.053463,0.003600,2.710271,1.80011,0.0,11:12:49
255,12765333,26657514,Zerodha,2024-10-22 00:00:00,NSE,J&KBANK,SELL,35,93.55,15.0,0.097245,0.006548,2.718683,3.27425,0.0,12:12:49

In [3]:
df_prices = pd.read_excel("../pandas-trader/stock_trader.xlsx", sheet_name='PRICES')
df_prices.tail()

,Unnamed: 0,Symbol,Company,Price,Category,52wk Low,52wk High
166,NaN,WELCORP,Welspun Corp Limited,772.85,Small Cap,440.15,794.75
167,NaN,WESTLIFE,Westlife Foodworld Limited,777.05,Small Cap,708.95,957.00
168,NaN,ZEEL,Zee Entertainment Enterprises Limited,123.36,Mid Cap,116.98,299.70
169,NaN,ZFCVINDIA,Zf Commercial Vehicle Control Systems India Li...,14491.15,Small Cap,12975.00,18250.00
170,NaN,ZYDUSWELL,Zydus Wellness Limited,1946.35,Small Cap,1440.15,2484.00

In [4]:
df = pd.merge(df_trader, df_prices, left_on='Scrip', right_on='Symbol').loc[:,['Company', 'Scrip', 'Transaction Date', 'Order Direction', 'Quantity', 'Share Price (₹)', '52wk Low', '52wk High']]
df

,Company,Scrip,Transaction Date,Order Direction,Quantity,Share Price (₹),52wk Low,52wk High
0,Interglobe Aviation Limited,INDIGO,2019-07-11,buy,10,1360.10,2486.25,5035.00
1,Bajaj Auto Limited.,BAJAJ-AUTO,2019-08-19,buy,7,2750.95,5349.05,12774.00
2,Reliance Industries Limited,RELIANCE,2019-08-19,buy,10,1232.49,1149.03,1608.80
3,Jio Financial Services Limited,JIOFIN,2019-08-19,buy-demerger,10,60.51,213.80,394.70
4,Mahindra And Mahindra Limited,M&M,2019-08-19,buy,1,533.85,1473.55,3222.10
...,...,...,...,...,...,...,...,...
244,Aarti Industries Ltd,AARTIIND,2024-10-10 00:00:00,BUY,12,527.90,475.00,769.25
245,Indian Overseas Bank,IOB,2024-10-10 00:00:00,BUY,150,54.55,38.95,83.75
246,Gujarat Mineral Development Corporation Limited,GMDCLTD,2024-10-10 00:00:00,BUY,25,326.40,307.10,506.00
247,Gujarat Fluorochemicals Limited,FLUOROCHEM,2024-10-10 00:00:00,SELL,2,4585.00,2476.00,4880.95
248,Jammu And Kashmir Bank Limited,J&KBANK,2024-10-22 00:00:00,SELL,35,93.55,88.11,152.50

In [5]:
df.groupby('Scrip')